# Generated by Django 6.0.5 on 2026-05-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_order_city_order_customer_email_order_customer_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RECEIVED", "Received"),
                    ("VERIFIED", "Verified"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
