# Generated by Django 6.0.5 on 2026-05-26 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_contactmessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name_plural": "Addresses"},
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("WELCOME", "Welcome"),
                            ("ORDER_CONFIRMATION", "Order confirmation"),
                            ("ORDER_STATUS", "Order status"),
                            ("PAYMENT_STATUS", "Payment status"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("SENDING", "Sending"),
                            ("RETRYING", "Retrying"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="QUEUED",
                        max_length=15,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("from_email", models.CharField(max_length=255)),
                ("to_email", models.EmailField(max_length=254)),
                ("body_text", models.TextField()),
                ("body_html", models.TextField(blank=True)),
                ("backend", models.CharField(blank=True, max_length=255)),
                ("attachment_name", models.CharField(blank=True, max_length=255)),
                ("attachment_mimetype", models.CharField(blank=True, max_length=100)),
                ("attachment_data", models.BinaryField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("sending_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-queued_at"],
            },
        ),
    ]
