# Generated by Django 6.0.5 on 2026-06-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_faq"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g. DISCOUNT20", max_length=50, unique=True
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2, help_text="e.g. 20.00 for 20%", max_digits=5
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="available_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_percentage",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
