# Generated by Django 6.0.5 on 2026-06-11 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_coupon_product_available_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="variant",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="variant",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.product",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.product",
            ),
        ),
        migrations.DeleteModel(
            name="ProductVariant",
        ),
    ]
