# Generated by Django 6.0.5 on 2026-06-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_add_like_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="price_at_like",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
