# Generated by Django 6.0.5 on 2026-06-14 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="productembedding",
            new_name="insights_pr_embeddi_96fcfa_idx",
            old_name="insights_pro_embeddi_idx",
        ),
        migrations.RenameIndex(
            model_name="productembedding",
            new_name="insights_pr_embeddi_4ce1ff_idx",
            old_name="insights_pro_embeddi_2_idx",
        ),
        migrations.RenameIndex(
            model_name="productembedding",
            new_name="insights_pr_updated_4954c6_idx",
            old_name="insights_pro_updated_idx",
        ),
    ]
