# Generated by Django 6.0.5 on 2026-06-14 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "insights",
            "0002_rename_insights_pro_embeddi_idx_insights_pr_embeddi_96fcfa_idx_and_more",
        ),
        ("store", "0014_add_price_snapshot_to_like"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="productembedding",
            name="insights_pr_embeddi_96fcfa_idx",
        ),
        migrations.AlterField(
            model_name="productembedding",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="productembedding",
            name="embedding_name",
            field=models.CharField(default="qwen3-embedding", max_length=255),
        ),
        migrations.AlterField(
            model_name="productembedding",
            name="embedding_source",
            field=models.CharField(
                choices=[("ollama", "Ollama Local"), ("manual", "Manual")],
                default="ollama",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="productembedding",
            name="embedding_vector",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productembedding",
            name="embedding_version",
            field=models.CharField(default="0.6b", max_length=50),
        ),
        migrations.AlterField(
            model_name="productembedding",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="embedding",
                to="store.product",
            ),
        ),
        migrations.RemoveField(
            model_name="productembedding",
            name="created_by",
        ),
    ]
