# Generated by Django 6.0.5 on 2026-06-18 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "insights",
            "0003_remove_productembedding_insights_pr_embeddi_96fcfa_idx_and_more",
        ),
        ("store", "0015_remove_cart_session_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("embedding_vector", models.JSONField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="store.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category Embedding",
                "verbose_name_plural": "Category Embeddings",
            },
        ),
        migrations.CreateModel(
            name="UserSemanticProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preference_vector", models.JSONField(blank=True, null=True)),
                ("category_interests", models.JSONField(blank=True, default=dict)),
                ("product_interests", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semantic_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Semantic Profile",
                "verbose_name_plural": "User Semantic Profiles",
            },
        ),
    ]
