# Generated by Django 6.0.5 on 2026-06-18 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0004_categoryembedding_usersemanticprofile"),
        ("store", "0015_remove_cart_session_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDemand",
            fields=[],
            options={
                "verbose_name": "Demand & Stock Forecast",
                "verbose_name_plural": "Demand & Stock Forecasts",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("store.product",),
        ),
    ]
