# Generated by Django 6.0.5 on 2026-06-18 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0005_productdemand"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductDemand",
        ),
    ]
